contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #configureinput channel"
    url: https://nfcore.slack.com/channels/configureinput
    about: Discussion about the nf-core/configureinput pipeline
